[profile.release]
strip = "symbols"
opt-level = "z"   # optimize for binary size
lto = true        # link time optimization
panic = "abort"
codegen-units = 1

[workspace]
resolver = "2"
default-members = ["src"]
members = ["helpers/print-key", "src", "vendor/pty", "vendor/vt100"]

[workspace.lints.clippy]
all = "allow"
